export enum actionTypes {
  GET_COVID_STATS_DATA = 'GET_COVID_STATS_DATA',
  FETCHING_COVID_STATS_DATA = 'FETCHING_COVID_STATS_DATA',
  FETCHING_COVID_STATS_DATA_SUCCESS = 'FETCHING_COVID_STATS_DATA_SUCCESS',
  FETCHING_OVID_STATS_DATA_FAILURE = 'FETCHING_OVID_STATS_DATA_FAILURE',
}
